version: '2'

services:
  wordpress:
    image: wordpress:4.5
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
    restart: always

  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - "./volumes/db:/var/lib/mysql"
    restart: always
